#!/bin/sh
# Supposed to open clj in another Terminal tab using the
# newtab function defined in ~/bin/definenewtab based on 
# https://stackoverflow.com/a/12147804/1455243

# Allows opening new Terminal tab:
source ~/bin/definenewtab

newtab src/scripts/cljWithCD

